# Generated by Django 6.0.4 on 2026-04-09 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('YouTube', 'YouTube'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Unknown', 'Unknown')], max_length=20)),
                ('source', models.CharField(choices=[('sentiment_dataset', 'Sentiment Dataset'), ('mediarates_dataset', 'Media Rates Dataset'), ('viral_trends_dataset', 'Viral Trends Dataset')], max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('post_time', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('is_weekend', models.BooleanField(default=False)),
                ('content_type', models.CharField(blank=True, choices=[('Video', 'Video'), ('Image', 'Image'), ('Text', 'Text'), ('Live', 'Live')], max_length=10, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('shares', models.IntegerField(default=0)),
                ('views', models.BigIntegerField(blank=True, null=True)),
                ('engagement_rate', models.FloatField(blank=True, null=True)),
                ('engagement_level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sosyal Medya Gönderisi',
                'verbose_name_plural': 'Sosyal Medya Gönderileri',
                'ordering': ['-date', '-post_time'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('content_based', 'İçerik Bazlı'), ('performance_based', 'Performans Bazlı')], max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=20, null=True)),
                ('goal', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(default='tr', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='uploads/csv/')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analiz',
                'verbose_name_plural': 'Analizler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_post_time', models.IntegerField(blank=True, null=True)),
                ('best_day', models.IntegerField(blank=True, null=True)),
                ('avg_engagement_rate', models.FloatField(blank=True, null=True)),
                ('avg_likes', models.FloatField(blank=True, null=True)),
                ('avg_comments', models.FloatField(blank=True, null=True)),
                ('avg_shares', models.FloatField(blank=True, null=True)),
                ('trend_fit_score', models.FloatField(blank=True, null=True)),
                ('heatmap_data', models.JSONField(blank=True, null=True)),
                ('content_type_performance', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysis')),
            ],
            options={
                'verbose_name': 'Analiz Sonucu',
                'verbose_name_plural': 'Analiz Sonuçları',
            },
        ),
    ]
